content:
  - name: blog
    label: Blog
    path: src/content/posts
    type: collection
    filename: '{fields.slug}.md'
    fields:
      - name: title
        label: Title
        type: string

      - name: slug
        label: Slug
        type: string

      - name: author
        label: Author
        type: string

      - name: pubDate
        label: Publication Date
        type: date

      - name: description
        label: Description
        type: text

      - name: metaTitle
        label: SEO Meta Title
        type: string

      - name: metaDescription
        label: SEO Meta Description
        type: text

      - name: focusKeyword
        label: Focus Keyword
        type: string

      - name: featuredImage
        label: Featured Image
        type: image
        options:
          path: src/assets/blog
          publicPath: /assets/blog

      - name: featuredImageAlt
        label: Featured Image Alt Text
        type: string

      - name: ogImage
        label: Open Graph Image URL
        type: string

      - name: twitterCard
        label: Twitter Card Type
        type: string
        options:
          - summary
          - summary_large_image

      - name: canonicalUrl
        label: Canonical URL
        type: string

      - name: hreflang
        label: "Hreflang ℹ️ (Language tag e.g. en-us, ur, ar)"
        type: string

      - name: ctaHeading
        label: CTA Heading
        type: string

      - name: ctaText
        label: CTA Text
        type: text

      - name: ctaButtonLabel
        label: CTA Button Label
        type: string

      - name: ctaButtonUrl
        label: CTA Button URL
        type: string

      - name: tags
        label: Tags
        type: string
        list: true

      - name: faqs
        label: FAQs
        type: object
        list: true
        fields:
          - name: question
            label: Question
            type: string
          - name: answer
            label: Answer
            type: text

      - name: body
        label: Body
        type: rich-text
        options:
          path: src/assets/blog
          extensions: [jpg, jpeg, png, webp]